# -*- coding: utf-8 -*-
"""olg_deterministic_kitao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17axwfxEdf1xyeb-bns3mrdr2D0rijYnW
"""

import numpy as np
import pandas as pd
from scipy.optimize import fsolve
import matplotlib.pyplot as plt

# シナリオごとの最適経路を解く関数

def solve_scenario(ind_E):
    """与えられたシナリオ番号 ind_E に対して
    - 資産パス a_j
    - 消費パス c_j
    - 年齢グリッド
    を辞書で返す。
    """

    # 基本パラメータ
    alpha = 0.40          # 資本の所得分配率
    delta = 0.08          # 資本減耗率
    beta  = 0.98         # 割引因子
    #beta  = 0.9          # 割引因子

    # ライフサイクル設定（シナリオによって上書きあり）
    Nj  = 61              # 生涯期間（20〜80 歳 → 61 期）
    NjW = 45              # 労働期間（20〜65 歳）
    psi = 0.5             # 年金の所得代替率

    # シナリオ別のパラメータ変更
    if ind_E == 0:
        pass
    elif ind_E == 1:        # 所得代替率を半減
        psi = 0.25
    elif ind_E == 2:      # 定年引上げ
        NjW = 50          # 労働 50 期（71 歳引退、年金受給者/総人口が減少、労働者/総人口が増加）
    elif ind_E == 3:      # 高齢化(年金受給者/総人口が増加、労働者/総人口が減少）
        Nj = 66           # 20〜85 歳 → 66 期、NjW（労働機関）はベースラインのまま（45 期）

    elif ind_E == 4:     # 生涯現役、死ぬまで働く
        NjW = Nj         # 退職しない
        psi = 0          # 年金給付なし




    # 人口分布と労働供給
    meaJ = np.ones(Nj) / Nj           # 各年代の人口
    if ind_E == 3:
        meaJ = np.ones(Nj) / 61.0     # シナリオ3では長寿化とともに人口が増加

    theta = np.zeros(Nj) # 労働生産性
    theta[:NjW] = 1.0    # 就業期間は労働生産性１、退職すると０
    #theta[:NjW] = np.linspace(0.01, 0.01 * (NjW - 1), NjW )

    L = np.sum(meaJ[:NjW] * theta[:NjW])  # 総労働供給

    # 年金
    ss0 = np.zeros(Nj)      # 年金所得代替率ベクトル
    ss0[NjW:] = psi         # 引退後に年金給付
    tau = psi * (Nj - NjW) / NjW   # 政府の収支をバランスさせる保険料率

    # 資産パスの初期推測
    a_guess = np.linspace(0.01, 0.01 * (Nj - 2), Nj - 1)


    # Euler 方程式の残差関数
    def path_asset(aX: np.ndarray) -> np.ndarray:
        """aX = (a₂,…,a_Nj)  を入力し Euler Error を返す。"""
        a = np.zeros(Nj + 1)   # a₁,…,a_{Nj+1}; 端点 a₁ = a_{Nj+1} = 0
        a[1:Nj] = aX

        # 要素価格（Ks=kd,Ls=Ldを暗黙に仮定）
        K = np.sum(a[:Nj] * meaJ) # 資本ストック供給を計算
        r = alpha * (K / L) ** (alpha - 1) - delta # 資本ストック市場のクリアリングを使う
        w = (1 - alpha) * (K / L) ** alpha # 労働ストック市場のクリアリングを使う
        ss = ss0 * w    # 年金給付額

        # 残差ベクトル
        f = np.empty(Nj - 1)
        for j in range(Nj - 1):   # j=0,…,Nj‑2
            c_now  = (1 + r) * a[j]     + w * (1 - tau) * theta[j]     + ss[j]     - a[j + 1]
            c_next = (1 + r) * a[j + 1] + w * (1 - tau) * theta[j + 1] + ss[j + 1] - a[j + 2]
            f[j] = c_next - beta * (1 + r) * c_now  # Euler Error
        return f

    # fsolve で Euler Error = 0 を満たす資産パスを探索
    a_solve, info, ier, msg = fsolve(path_asset, a_guess, full_output=True) # 解ベクトル、追加情報（反復回数等）、正常に収束したか（１なら正常）、収束可否の説明
    if ier != 1:
        raise RuntimeError(f"fsolve failed (scenario {ind_E}): {msg}")

    # 導出した資産パスに１期とNj+1期を追加
    a_new = np.zeros(Nj + 1) # 端点 a₁ = a_{Nj+1} = 0
    a_new[1:Nj] = a_solve

    # 資産パスに基づき再計算
    K_new = np.sum(a_new[:Nj] * meaJ)
    r_new = alpha * (K_new / L) ** (alpha - 1) - delta
    w_new = (1 - alpha) * (K_new / L) ** alpha
    ss_new = ss0 * w_new
    ss_total = np.sum(ss_new)

    c_path = (1 + r_new) * a_new[:Nj] + w_new * (1 - tau) * theta + ss_new - a_new[1:]
    income_path=r_new * a_new[:Nj] + w_new * (1 - tau) * theta + ss_new
    # 年齢グリッド（20 歳から）
    age_Asset = np.arange(1, Nj + 2) + 19   # a₁,…,a_{Nj+1}
    age_Consumption = np.arange(1, Nj + 1) + 19   # c₁,…,c_Nj
    #print('beta*(1+r): ',beta*(1+r_new))

    return {
        "ageA": age_Asset,
        "assets": a_new,
        "ageC": age_Consumption,
        "consumption": c_path,
        "norm": c_path[0],  # 初期消費（正規化定数）
        "income_path":income_path,
        "K": K_new,
        "K/L":K_new/L,
        "r": r_new,
        "w": w_new,
        "tau":tau,
        "ss_total":ss_total,

    }

# Baseline を解く
Baseline_result = solve_scenario(0)

# プロット
plt.figure("Assets", figsize=(8, 5))
plt.plot(Baseline_result["ageA"], Baseline_result["assets"] / Baseline_result["norm"])
plt.xlabel("Age")
plt.ylabel("Asset")
plt.title("Asset")
plt.grid(True)
plt.box(True)


plt.figure("income", figsize=(8, 5))
plt.plot(Baseline_result["ageC"], Baseline_result["income_path"] / Baseline_result["norm"])
plt.xlabel("Age")
plt.ylabel("income")
plt.title("income")
plt.grid(True)
plt.box(True)

plt.figure("Consumption", figsize=(8, 5))
plt.plot(Baseline_result["ageC"], Baseline_result["consumption"] / Baseline_result["norm"])
plt.xlabel("Age")
plt.ylabel("Consumption")
plt.title("Consumption")
plt.grid(True)
plt.box(True)

plt.show()

# 生涯現役を解く
work_result = solve_scenario(4)

# プロット
plt.figure("Assets")
plt.plot(work_result["ageA"], work_result["assets"] / work_result["norm"])
plt.xlabel("Age")
plt.ylabel("Asset")
plt.title("Asset")
plt.grid(True)
plt.box(True)

plt.figure("income")
plt.plot(work_result["ageC"], work_result["income_path"] / work_result["norm"])
plt.xlabel("Age")
plt.ylabel("income")
plt.title("income")
plt.grid(True)
plt.box(True)

plt.figure("Consumption")
plt.plot(work_result["ageC"], work_result["consumption"] / work_result["norm"])
plt.xlabel("Age")
plt.ylabel("Consumption")
plt.title("Consumption")
plt.grid(True)
plt.box(True)



plt.show()

# すべてのシナリオを解いて結果を集計
scenarios = {
    0: "Baseline",
    1: "1: Lower replacement rate",
    2: "2: Retire at 71",
    3: "3: Live to 85",
    4: "4: Work until death",
}

results = {k: solve_scenario(k) for k in scenarios}
baseline = results[0]

rows = []
for k, name in scenarios.items():
    res = results[k]
    rows.append({
        'Scenario': name,
        'K': 100*(res['K'] - baseline['K'])/baseline['K'],
        'K/L': 100*(res['K/L'] - baseline['K/L'])/baseline['K/L'],
        'r': 100*res['r'],
        'w': 100*(res['w'] - baseline['w'])/baseline['w'],
        'tau': 100*res['tau'],
        'ss_total': res['ss_total'],
    })
df= pd.DataFrame(rows)
for col in ['K','K/L', 'w']:
    df[col] = df[col].apply(lambda x: f"{x:+.1f}%")
for col in ['r', 'tau']:
    df[col] = df[col].apply(lambda x: f"{x:.1f}%")
df

# Baselineの初期消費で正規化
base_norm = results[0]["norm"]

# プロット
plt.figure("Assets – four scenarios", figsize=(8, 5))
for k, res in results.items():
    plt.plot(res["ageA"], res["assets"] / base_norm, label=scenarios[k], linewidth=2)
plt.xlabel("Age")
plt.ylabel("Asset")
plt.title("Asset comparison")
plt.legend()
plt.grid(True)
plt.box(True)

plt.figure("Consumption – four scenarios", figsize=(8, 5))
for k, res in results.items():
    plt.plot(res["ageC"], res["consumption"] / base_norm, label=scenarios[k], linewidth=2)
plt.xlabel("Age")
plt.ylabel("Consumption")
plt.title("Consumption comparison")
plt.legend()
plt.grid(True)
plt.box(True)

plt.show()

